### PR TITLE
Add sending transaction function

### PR DESCRIPTION
**Pull request by grorge123**

### CODE REVIEW

**Comment by grorge123** [comment]
This function can correctly send transactions on the sepolia testnet and arbitrum sepolia testnet. 
On the ploygon mumbai testnet, this function can get transaction hash from provider, but the transaction will not be recorded on the blockchain.

**Comment by juntao** [comment]
Sorry for the delay. But why would it not work on polygon? Thanks.

**Comment by grorge123** [comment]
I'm currently unsure of the exact cause of the issue. As far as I know, the transaction formats for Sepolia and Mumbai should be the same. Additionally, after sending a transaction, the provider does return a transaction hash normally. However, subsequent queries result in a 'null' outcome, without any additional error messages.

**Comment by juntao** [comment]
Hmm. Could it be that you are not giving sufficient gas and the Tx is rejected by the miners?

**Comment by grorge123** [comment]
I tried again today. Although I'm not sure why there was a problem previously, the existing program now can correctly send transactions on the Polygon Mumbai network. However, to avoid too lower gas, I've increased the estimated gas.

**Pull request closed without merging**
