### PR TITLE
Add new function to ethereum-example

### PR DESCRIPTION
**Pull request by grorge123**
- get_balance
  - [x] Implementation
  - [x] Documentation
- get_txs
  - [x] Support CMT
  - [x] Support Other
  - [x] Documentation
- get_pbm_balance
  - [x] Implementation
  - [x] Documentation
- get_pbm_from_txs
  - [x] Implementation
  - [x] Documentation
- get_pbm_to_txes
  - [x] Implementation
  - [x] Documentation
- get_erc20_balance
  - [x] Support CMT
  - [x] Support Other
  - [x] Documentation
- get_erc20_from_txs
  - [x] Support CMT
  - [x] Support Other
  - [x] Documentation
- get_erc20_to_txes
  - [x] Support CMT
  - [x] Support Other
  - [x] Documentation

### CODE REVIEW

**Comment by juntao** [comment]
I am trying to following the `get_pbm_balance` example. But my JSON-RPC always returns

```
 {\"jsonrpc\":\"2.0\",\"id\":1,\"error\":{\"code\":-32000,\"message\":\"execution reverted\"}}
```

This is on the CyberMiles RPC. 

Contract address: `0x8Ac7e7DB5DF09ED5403e5414e7AA39968cf9d80D`
Account address to query balanceOf: `0x84b5b41492bbe9d5c0d1951b9c78f784894d850f`

ABI:

```
[
        {
            "inputs": [
                {"internalType": "address", "name": "user", "type": "address"}
            ],
            "name": "balanceOf",
            "outputs": [
                {"internalType": "uint256", "name": "", "type": "uint256"}
            ],
            "stateMutability": "view",
            "type": "function"
        }
    ]
```


Can you also check? Thanks!

**Comment by grorge123** [comment]
> I am trying to following the `get_pbm_balance` example. But my JSON-RPC always returns
> 
> ```
>  {\"jsonrpc\":\"2.0\",\"id\":1,\"error\":{\"code\":-32000,\"message\":\"execution reverted\"}}
> ```
> 
> This is on the CyberMiles RPC.
> 
> Contract address: `0x8Ac7e7DB5DF09ED5403e5414e7AA39968cf9d80D` Account address to query balanceOf: `0x84b5b41492bbe9d5c0d1951b9c78f784894d850f`
> 
> ABI:
> 
> ```
> [
>         {
>             "inputs": [
>                 {"internalType": "address", "name": "user", "type": "address"}
>             ],
>             "name": "balanceOf",
>             "outputs": [
>                 {"internalType": "uint256", "name": "", "type": "uint256"}
>             ],
>             "stateMutability": "view",
>             "type": "function"
>         }
>     ]
> ```
> 
> Can you also check? Thanks!

This problem is because querying the balance is a function that will be updated later. In addition, I created a PR for adding event to get pbm txs.
It can be fixed by deploying the latest contract and new flows function.

**Comment by juntao** [comment]
Ok. Thanks. Let me know when the PBM balance query is working. Would like to try it out.

**Comment by grorge123** [comment]
I apologize for the confusion in my previous wording. The balance query feature has already been merged into the main branch, so you can simply use the latest contract as it is now. Thank you.

**Comment by juntao** [comment]
Do you mean that I should create a new PBM contract using the latest SOL code. And the Rust code I have above would work to get the PBM account balance? Thanks.

**Comment by grorge123** [comment]
Yes, just deploy the latest PBM solidity code. To read the PBM event information, please use the rust code after the commit 5be67bc1640298904ef24c4e4c3519fbef013021. If there still have  any problem, please let me know, thank you.

**Comment by juntao** [comment]
> Yes, just deploy the latest PBM solidity code. To read the PBM event information, please use the rust code after the commit [5be67bc](https://github.com/flows-network/ethereum-example/commit/5be67bc1640298904ef24c4e4c3519fbef013021). If there still have any problem, please let me know, thank you.

No luck. At this stage, I need to get the coin balance first before I can make use of the transaction history.

1 We deployed a new PBM contract using the latest SOL code. The contract address is `0x9072Ec82ABD363D892Fd8A4A2e31165183577747`

https://cmttracking.io/address/0x9072Ec82ABD363D892Fd8A4A2e31165183577747

2 We called `fundUser()` on the PBM for address `0xd3ad6fea094f46a5317d8d4820ee11a61fa2f6ff`. It was successful and the PBM contract shows a balance of 20 ERC20 tokens.

https://cmttracking.io/token/0x69d388C32BCDC33D38846087317457A49f52dB20/token-holders

3 We used your code to call `balanceOf()`, but it was not successful. Example code:

```
let contract_abi: &str = r#"[
        {
            "inputs": [
                {"internalType": "address", "name": "user", "type": "address"}
            ],
            "name": "balanceOf",
            "outputs": [
                {"internalType": "uint256", "name": "", "type": "uint256"}
            ],
            "stateMutability": "view",
            "type": "function"
        }
]"#;
let abi: Abi = serde_json::from_str(contract_abi).unwrap();
let function: &Function = abi
        .functions()
        .find(|&f| f.name == "balanceOf")
        .ok_or("Function not found in ABI")?;

let tokens = vec![Token::Address(user_address)];
let data = Bytes::from(function.encode_input(&tokens).unwrap());

let params = json!([{
        "from": "0x0000000000000000000000000000000000000000",
        "to": &pool_address,
        "data": format!("{:}", data).as_str()}, "latest"]);
let result = json_rpc(&rpc_node_url, "eth_call", params).await.expect("Failed to send json.");
```

The request is 

```
Object {\n \"id\": Number(1),\n \"jsonrpc\": String(\"2.0\"),\n \"method\": String(\"eth_call\"),\n \"params\": Array [\n Object {\n \"data\": String(\"0x70a08231000000000000000000000000d3ad6fea094f46a5317d8d4820ee11a61fa2f6ff\"),\n \"from\": String(\"0xd3ad6fea094f46a5317d8d4820ee11a61fa2f6ff\"),\n \"to\": String(\"0x9072Ec82ABD363D892Fd8A4A2e31165183577747\"),\n },\n String(\"latest\"),\n ],\n}
```

The response is

```
{\n \"id\": Number(1),\n \"error\": Object {\n \"code\": Number(-32000),\n \"message\": String(\"execution reverted\"),\n },\n \"jsonrpc\": String(\"2.0\"),\n}
```

What do you think?

**Comment by grorge123** [comment]
In the CMT tracking, I see the contract still is the old version, there is no `balanceOf` function in the Contract source code. https://cmttracking.io/address/0x9072Ec82ABD363D892Fd8A4A2e31165183577747/contracts

But in the latest source code, I have added `balaceOf` function to the contract source code.
https://github.com/coda-bridge/pbm-pilot/blob/main/PBM.sol
The new version of pbm in the CMT tracking is like this.
https://cmttracking.io/address/0xb1C1cEE9952e99f1d114f80E6a17fD598Ef106Af
I guess there are some problems with the deployment pbm contract. Can you help me to check the `PBM.sol` int the `hardhat/contracts`? Thank you.

**Comment by juntao** [comment]
You are right! I am sorry. This was a very stupid mistake on my end.

**Comment by juntao** [comment]
I am able to get token balances in the PBM contract now. Thank you.

I noticed that you are using on-chain events to get PBM tx histories, but using the CMT API to get ERC20 tx histories. I believe the ERC20 `transfer` function would also generate an event. Why not use events for ERC20 histories as well?

**Comment by juntao** [comment]
In the function to get PBM tx history, there is a hardcoded string 

`0x34882e90c95bfeaeb7e0738cfd8af3d1f6ab3d2065dd70f6660b404b9beb3505`

What is it for? Thanks.

**Comment by grorge123** [comment]
This is "payEvent(uint256,address,address,uint256)" using keccak-256 encoding. It is for query event filter. I will update the code comment later.

**Comment by grorge123** [comment]
> I am able to get token balances in the PBM contract now. Thank you.
> 
> I noticed that you are using on-chain events to get PBM tx histories, but using the CMT API to get ERC20 tx histories. I believe the ERC20 `transfer` function would also generate an event. Why not use events for ERC20 histories as well?

Sorry for late reply. Quering on-chain events API returns one contract result once. But CMT API can return all the result at once.

**Comment by grorge123** [comment]
The above work has been completed. Thank you.

**Review by juntao — APPROVED** [review]

**Comment by juntao** [comment]
Thank you!

**Pull request merged**
